import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;

const downloadBlob = (bytes, fileName) => {
  const blob = new Blob([bytes], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  link.click();
  URL.revokeObjectURL(url);
};

const wrapText = (text, font, size, maxWidth) => {
  const words = String(text || "").split(/\s+/);
  const lines = [];
  let currentLine = "";

  words.forEach((word) => {
    const nextLine = currentLine ? `${currentLine} ${word}` : word;
    if (font.widthOfTextAtSize(nextLine, size) <= maxWidth) {
      currentLine = nextLine;
    } else {
      if (currentLine) lines.push(currentLine);
      currentLine = word;
    }
  });

  if (currentLine) lines.push(currentLine);
  return lines;
};

export const downloadSynapXReport = async ({
  title,
  patient = {},
  fields = [],
  prediction,
  fileName,
}) => {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  page.drawRectangle({
    x: 0,
    y: PAGE_HEIGHT - 132,
    width: PAGE_WIDTH,
    height: 132,
    color: rgb(0.05, 0.07, 0.11),
  });

  page.drawRectangle({
    x: 0,
    y: PAGE_HEIGHT - 136,
    width: PAGE_WIDTH,
    height: 4,
    color: rgb(0.31, 0.82, 0.77),
  });

  page.drawText("SynapX", {
    x: 48,
    y: PAGE_HEIGHT - 58,
    size: 30,
    font: boldFont,
    color: rgb(0.96, 0.98, 1),
  });

  page.drawText("AI Diagnostic Suite", {
    x: 50,
    y: PAGE_HEIGHT - 82,
    size: 11,
    font: regularFont,
    color: rgb(0.69, 0.75, 0.82),
  });

  page.drawText(title, {
    x: 48,
    y: PAGE_HEIGHT - 164,
    size: 20,
    font: boldFont,
    color: rgb(0.06, 0.09, 0.14),
  });

  let y = PAGE_HEIGHT - 205;
  const writeSectionTitle = (text) => {
    page.drawText(text, {
      x: 48,
      y,
      size: 12,
      font: boldFont,
      color: rgb(0.06, 0.09, 0.14),
    });
    y -= 22;
  };

  const writeRow = (label, value) => {
    page.drawText(label, {
      x: 58,
      y,
      size: 11,
      font: boldFont,
      color: rgb(0.2, 0.25, 0.33),
    });

    const lines = wrapText(value || "-", regularFont, 11, 310);
    lines.forEach((line, index) => {
      page.drawText(line, {
        x: 220,
        y: y - index * 15,
        size: 11,
        font: regularFont,
        color: rgb(0.08, 0.1, 0.14),
      });
    });

    y -= Math.max(20, lines.length * 15 + 5);
  };

  writeSectionTitle("Patient Details");
  Object.entries(patient).forEach(([label, value]) => writeRow(label, value));

  y -= 8;
  writeSectionTitle("Clinical Inputs");
  fields.forEach(({ label, value }) => writeRow(label, value));

  y -= 12;
  page.drawRectangle({
    x: 48,
    y: y - 64,
    width: PAGE_WIDTH - 96,
    height: 76,
    color: rgb(0.93, 0.98, 0.98),
    borderColor: rgb(0.31, 0.82, 0.77),
    borderWidth: 1.2,
  });

  page.drawText("Prediction Result", {
    x: 64,
    y: y - 16,
    size: 12,
    font: boldFont,
    color: rgb(0.04, 0.36, 0.34),
  });

  const resultLines = wrapText(prediction || "-", regularFont, 13, PAGE_WIDTH - 136);
  resultLines.forEach((line, index) => {
    page.drawText(line, {
      x: 64,
      y: y - 40 - index * 17,
      size: 13,
      font: regularFont,
      color: rgb(0.06, 0.09, 0.14),
    });
  });

  page.drawText("Generated by SynapX", {
    x: 48,
    y: 42,
    size: 10,
    font: regularFont,
    color: rgb(0.45, 0.5, 0.58),
  });

  const pdfBytes = await pdfDoc.save();
  downloadBlob(pdfBytes, fileName);
};
